# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: devel
cache: packages
after_success:
  - Rscript -e 'covr::codecov(line_exclusions = "R/internal-widgets.R")'
